# Generated by Django 2.1.1 on 2019-02-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=1000)),
                ('token', models.CharField(max_length=1000)),
            ],
        ),
    ]
