# Generated by Django 2.1.1 on 2019-02-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(default=None, max_length=12),
            preserve_default=False,
        ),
    ]
