# Generated by Django 2.1.7 on 2019-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20190208_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='premium',
            field=models.BooleanField(default=True),
        ),
    ]
