# Generated by Django 2.1.1 on 2019-02-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.DecimalField(decimal_places=1, default=0.0, max_digits=1000)),
                ('notice', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
