# Generated by Django 2.1.7 on 2019-07-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegram_id',
            name='sub',
            field=models.BooleanField(default=False),
        ),
    ]
